### ISSUE TITLE
Hello, welcome for any feedbacks

### ISSUE THREAD

**Issue by pablocc1979** [pablocc1979/Green-Hub-Proxy#1]
pls

**Comment by Coder-Leon** [comment]
when I was opened the Chrome,there was always opened the GreenHub-setting-page meanwhile.

**Comment by StellaSue** [comment]
May I ask if this proxy can't connect currently or there is a problem about my explorer ?
![8sw4zs ng gul8h 3dr l](https://user-images.githubusercontent.com/30014547/27991352-4fda373c-64a6-11e7-9226-cce4d50732b2.png)

**Comment by jonstic** [comment]
![greenhub](https://user-images.githubusercontent.com/29301880/27992226-8a381370-64c1-11e7-98f5-d8a2c55d2b14.png)

站长，麻烦处理错误啊。。Thanks..

**Comment by pablocc1979** [comment]
All resolved


Thanks ~

**Comment by saysomethingtoyou** [comment]
![image](https://user-images.githubusercontent.com/12441050/29703642-ed6b482a-89a8-11e7-98d6-d94ef5a04884.png)
Can't to connect

**Comment by pablocc1979** [comment]
Got your feedback.  Because one network node is blocked by GFW firewall.

This issue will be solved in this week.

@saysomethingtoyou   Thanks for your support and message!

**Comment by wellylau** [comment]
![](https://user-images.githubusercontent.com/12441050/29703642-ed6b482a-89a8-11e7-98d6-d94ef5a04884.png)
还是无法连接，什么时候能好起来

**Comment by saysomethingtoyou** [comment]
@pablocc1979 It's OK,thanks!

**Comment by wellylau** [comment]
￼
![wechatimg5 1](https://user-images.githubusercontent.com/31388880/29802737-c9b18e40-8ca9-11e7-8847-3947b1e03f11.jpeg)
刚刚发生的，这是怎么回事？难道以后不能用了吗？

**Comment by pablocc1979** [comment]
@wellylau Problem resolved. 
Now it is available to use. Thanks a lot ~~~ 

PS,  will be figuring out one new distributed approach to avoid GFW's potential blocking in the near future.

**Comment by caloblee** [comment]
please help to check the problem

**Comment by caloblee** [comment]
please help to solve the problem
由于政策原因，我们服务器被迫暂停
![360 20171011213928](https://user-images.githubusercontent.com/29850631/33072380-483371ec-cefa-11e7-88fb-78500ba4741e.jpg)

**Comment by wmjtxt** [comment]
#13

**Comment by dingww** [comment]
Somebody's are well, but there is still some wrong in my web.
![image](https://user-images.githubusercontent.com/17487060/39407582-8e6ba8d2-4bfa-11e8-9c55-8d7073020100.png)

**Comment by ajing1234** [comment]
我也出现了楼上一样的问题，请问要怎么解决？
![default](https://user-images.githubusercontent.com/36064814/43998687-07f1691e-9e2e-11e8-959a-750252ecde08.PNG)

**Comment by ghotst0xdeadbeef** [comment]
先close了
