### ISSUE TITLE
桌面版怎么付费后仍使用不了

### ISSUE THREAD

**Issue by iwanttosleepzZ** [pablocc1979/Green-Hub-Proxy#110]
issue：为什么我的桌面版买了一年套餐，用了几天就无法再用了，而且激活码激活不了？？？？？
If it is possible，i want to get my money back！！

**Comment by lgzjbd** [comment]
我也遇到了这样的问题，请问你解决了吗？

**Comment by Yxu-boop** [comment]
我的也是，请问解决了吗，感觉被骗了，激活不了，怎么取消续订啊

**Comment by LJY010821** [comment]
我也是，最后怎么解决的啊

**Comment by Xin-Dai** [comment]
我也遇到了同样的问题，请问解决了吗

**Comment by reAsuka5201314** [comment]
请问您解决了吗，楼上几位呢

**Comment by reAsuka5201314** [comment]
> issue：为什么我的桌面版买了一年套餐，用了几天就无法再用了，而且激活码激活不了？？？？？ If it is possible，i want to get my money back！！



> 我也遇到了这样的问题，请问你解决了吗？

你们解决了吗
