### ISSUE TITLE
连接不上！提示设置错误！

### ISSUE THREAD

**Issue by 1710085193** [pablocc1979/Green-Hub-Proxy#14]
![qq 20180217194955](https://user-images.githubusercontent.com/36564439/36340590-96fd480a-141b-11e8-97ae-09709a3691e5.png)

**Comment by leiyang8852** [comment]
How to solve this problem

**Comment by tiantangzhiyue** [comment]
我也出现了这个问题

**Comment by JeanLaw** [comment]
我的也是这样0.0

**Comment by pablocc1979** [comment]
Solved.
thanks
