### ISSUE TITLE
2018 Q3 Good news: Solved issues and add new vpn nodes

### ISSUE THREAD

**Issue by pablocc1979** [pablocc1979/Green-Hub-Proxy#17]
Sorry for late reply. Because recently I am very busy

Good news: I have added 2 vpn nodes.

Thanks for your long long support.
Please share it with your friends if you feel happy about the FAN-QIANG service

**Comment by pablocc1979** [comment]
thank :)

**Comment by ruboo3635** [comment]
谢谢
