### ISSUE TITLE
Can't use

### ISSUE THREAD

**Issue by AngelClever** [pablocc1979/Green-Hub-Proxy#19]
can't load Facebook and youtube 
there might be some error

**Comment by AngelClever** [comment]
Well I have a try  this afternoon 
It works again
I can use my facebook again/

**Comment by ghotst0xdeadbeef** [comment]
Thanks for you support, please try the new 0.9 version.
https://github.com/pablocc1979/Green-Hub-Proxy/releases/tag/v0.9
