### ISSUE TITLE
如何将自己的SOKCS账号添加进去啊

### ISSUE THREAD

**Issue by becapital** [pablocc1979/Green-Hub-Proxy#22]
如何将自己的SOKCS账号添加进去啊？不想占用共享的账号！
感谢作者，真是超级简单，超级好用。良心啊，科研足够用了。

**Comment by ghotst0xdeadbeef** [comment]
感谢您的使用。目前我们还未支持自定义的代理节点，而且由于浏览器的安全限制，shadowsocks 等工具还不能很好的支持。
如果有自己搭建的节点，可以考虑 SwitchyOmega 插件来配合使用。
另外，也可以尝试我们新发布的 0.9 版本，更换了一批代理节点，速度更快 https://github.com/pablocc1979/Green-Hub-Proxy/releases/tag/v0.9
