### ISSUE TITLE
能用了

### ISSUE THREAD

**Issue by ruboo3635** [pablocc1979/Green-Hub-Proxy#26]

**Comment by keeplearning-again** [comment]
不能用啊，好像都加不了插件，说是无效

**Comment by muaXiaoNing** [comment]
> 不能用啊，好像都加不了插件，说是无效

我也是哇，是不是电脑32位的缘故？

**Comment by ghotst0xdeadbeef** [comment]
请尝试使用最新的 0.9 版本 https://github.com/pablocc1979/Green-Hub-Proxy/releases/tag/v0.9
