### ISSUE TITLE
在github下载的版本打开后提示到google商店更新，问题是大陆无法访问google也就无法更新

### ISSUE THREAD

**Issue by songsf520** [pablocc1979/Green-Hub-Proxy#27]
在github下载的版本打开后提示到google商店更新，问题是使用Green-Hub-Proxy因为无法访问google，无法更新导致无法使用，
建议尽快升级github版本，不要在google商店更新
![QQ浏览器截图20200731083907](https://user-images.githubusercontent.com/35684963/88987878-e64a0b00-d309-11ea-90d0-bd23d65e0522.png)
![QQ浏览器截图20200731083922](https://user-images.githubusercontent.com/35684963/88987890-eba75580-d309-11ea-87dc-9a79be232945.png)

**Comment by ghotst0xdeadbeef** [comment]
请尝试我们发布的 0.9 最新版 https://github.com/pablocc1979/Green-Hub-Proxy/releases/tag/v0.9
