### ISSUE TITLE
macos 10.15 chrome浏览器无法用

### ISSUE THREAD

**Issue by ewingzhang** [pablocc1979/Green-Hub-Proxy#28]
macos 10.15 chrome浏览器无法用 点进去一直显示 “数据加载失败或操作过于频繁，请等待！”

**Comment by dongfeng2018** [comment]
遇到同样的问题，拖进扩展程序中提升错误
![1605405272153](https://user-images.githubusercontent.com/42435654/99161023-98c2a400-2728-11eb-9ace-33e2b07ebb46.jpg)

**Comment by ghotst0xdeadbeef** [comment]
请尝试最新的 0.9 版本。
