### ISSUE TITLE
请问如何在手机上用呢

### ISSUE THREAD

**Issue by chai13** [pablocc1979/Green-Hub-Proxy#29]
请问如何在手机上用呢

**Comment by ghotst0xdeadbeef** [comment]
移动端支持还在计划中，您可以点击 watch, 有结果后会同步到这个 repo.

**Comment by chai13** [comment]
> 移动端支持还在计划中，您可以点击 watch, 有结果后会同步到这个 repo.
已了解，谢谢回复
