### ISSUE TITLE
chrome 应用商店的插件已经被下架了 说是有害

### ISSUE THREAD

**Issue by KuiYang2017** [pablocc1979/Green-Hub-Proxy#30]
新版0.9 无法连接到服务器界面 
老版本地留存 chrome插件 2,6 正常

**Comment by ghotst0xdeadbeef** [comment]
@KuiYang2017 请问是否可以访问如下链接 https://static.greenhubex.tk/test.json

关于有害问题：旧版本支持期已过，有些陈旧代码已经不符合隐私规范，会被判定为有害行为。
商店中的版本已经被下架。0.9 版本在稳定之后也会发布在商店中。

**Comment by KuiYang2017** [comment]
新版本一开始不行 就是连接服务器那个页面会一直等待  现在可以没问题了 可以正常使用
