### ISSUE TITLE
为什么国内提示升级啊。上不了了

### ISSUE THREAD

**Issue by zxl546506** [pablocc1979/Green-Hub-Proxy#4]
1111111

**Comment by pablocc1979** [comment]
@zxl546506 被墙了。。。。我在想另外一个方案，彻底摆脱墙。

**Comment by wmjtxt** [comment]
"由于政策原因，我们的服务被迫暂停，请稍后尝试!"迎接19da吗

**Comment by pablocc1979** [comment]
@wmjtxt 。。。。。

**Comment by pablocc1979** [comment]
@zxl546506 @wmjtxt 可用了。
后面准备再做一个更好方案，永不被墙 :)

**Comment by edle123456789** [comment]
我本来准备了socks scanner, socks checker, proxy cap 准备自己解决的....
