### ISSUE TITLE
edge浏览器使用greenhub插件

### ISSUE THREAD

**Issue by supeep** [pablocc1979/Green-Hub-Proxy#47]
会显示需要登录，但好像不用管也能使用

**Comment by ghotst0xdeadbeef** [comment]
这个偶尔会提示登录，可以尝试关闭tab页重新打开，目前还没有找到太好的解决办法

**Comment by supeep** [comment]
好的，谢谢

ghotst0xdeadbeef ***@***.***> 于 2021年7月30日周五 09:50写道：

**Comment by foricons** [comment]
我不太会github问题提交，不过我知道这个问题的来源是因为代理的逻辑bug，当多个插件同时提供代理的时候（不一定非得是VPN，有些插件也会包含一些代理），由于插件安装顺序不同，插件的权重不同，导致权重低的代理会出现bug。似乎是最先安装的权重最高，所以需要第一个安装咱们的VPN插件。

**Comment by foricons** [comment]
> 这个偶尔会提示登录，可以尝试关闭tab页重新打开，目前还没有找到太好的解决办法
我不太会github问题提交，不过我知道这个问题的来源是因为代理的逻辑bug，当多个插件同时提供代理的时候（不一定非得是VPN，有些插件也会包含一些代理），由于插件安装顺序不同，插件的权重不同，导致权重低的代理会出现bug。只能一个个排除自己的插件是哪个产生了代理，我定位到的是我的哔哩哔哩助手产生了代理（最新更新版有一个推送的锅吧），网上https://blog.csdn.net/weixin_49519738/article/details/108929401提供了解决方案，但我不知道怎么添加这个API，还是麻烦作者去搞一下这个吧，有答案了麻烦通知我一下。
或者作者可以对插件进行升级改造，自动监测其他的代理并将其加入名单，不知道可不可行。

**Comment by ghotst0xdeadbeef** [comment]
感谢支持。 我按这个思路尝试下

> > 这个偶尔会提示登录，可以尝试关闭tab页重新打开，目前还没有找到太好的解决办法
> > 我不太会github问题提交，不过我知道这个问题的来源是因为代理的逻辑bug，当多个插件同时提供代理的时候（不一定非得是VPN，有些插件也会包含一些代理），由于插件安装顺序不同，插件的权重不同，导致权重低的代理会出现bug。只能一个个排除自己的插件是哪个产生了代理，我定位到的是我的哔哩哔哩助手产生了代理（最新更新版有一个推送的锅吧），网上[https://blog.csdn.net/weixin_49519738/article/details/108929401提供了解决方案，但我不知道怎么添加这个API，还是麻烦作者去搞一下这个吧，有答案了麻烦通知我一下。](https://blog.csdn.net/weixin_49519738/article/details/108929401%E6%8F%90%E4%BE%9B%E4%BA%86%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88%EF%BC%8C%E4%BD%86%E6%88%91%E4%B8%8D%E7%9F%A5%E9%81%93%E6%80%8E%E4%B9%88%E6%B7%BB%E5%8A%A0%E8%BF%99%E4%B8%AAAPI%EF%BC%8C%E8%BF%98%E6%98%AF%E9%BA%BB%E7%83%A6%E4%BD%9C%E8%80%85%E5%8E%BB%E6%90%9E%E4%B8%80%E4%B8%8B%E8%BF%99%E4%B8%AA%E5%90%A7%EF%BC%8C%E6%9C%89%E7%AD%94%E6%A1%88%E4%BA%86%E9%BA%BB%E7%83%A6%E9%80%9A%E7%9F%A5%E6%88%91%E4%B8%80%E4%B8%8B%E3%80%82)
> > 或者作者可以对插件进行升级改造，自动监测其他的代理并将其加入名单，不知道可不可行。
