### ISSUE TITLE
2021/09/05 12:25 使用不了 [代理错误]

### ISSUE THREAD

**Issue by fengapdi** [pablocc1979/Green-Hub-Proxy#54]
报错：

    你尚未连接
    代理服务器可能有问题，或地址不正确。

    请尝试：
        正在与你的组织联系
        检查代理地址
        运行 Windows 网络诊断
    ERR_PROXY_CONNECTION_FAILED

**Comment by fengapdi** [comment]
Edge和Chrome都使用不了...

本人ISP 浙江移动

**Comment by ghotst0xdeadbeef** [comment]
IP被和谐了，正在努力解决中

**Comment by fengapdi** [comment]
所有节点流量都已用尽
![image](https://user-images.githubusercontent.com/70789009/132967567-fdcd7829-4eae-476a-ace5-3ee24fc85635.png)

**Comment by ghotst0xdeadbeef** [comment]
可试用桌面版，插件端后面会尝试解决
https://github.com/ghotst0xdeadbeef/Greenhub-desktop/releases
