### ISSUE TITLE
2021-09-05节点状态异常

### ISSUE THREAD

**Issue by Hinghuai** [pablocc1979/Green-Hub-Proxy#55]
17：30
节点状态异常
连接节点后，网页无法正常打开，包括但不限于google.com

广东东莞移动

**Comment by merdan988** [comment]
节点状态异常
连接节点后，网页无法正常打开，包括但不限于google.com

广东东莞移动

**Comment by ghotst0xdeadbeef** [comment]
尝试下桌面版：https://github.com/ghotst0xdeadbeef/Greenhub-desktop/releases
插件端会在节后修复
