### ISSUE TITLE
插件端暂不可用，已经发布桌面版，支持win和mac

### ISSUE THREAD

**Issue by ghotst0xdeadbeef** [pablocc1979/Green-Hub-Proxy#60]
下载地址： https://github.com/ghotst0xdeadbeef/Greenhub-desktop/releases

**Comment by Ender-003** [comment]
似乎也用不了

**Comment by Ender-003** [comment]
哦,忘了这阵子敏感时期

**Comment by ghotst0xdeadbeef** [comment]
> 似乎也用不了

用不了么？ 是所有节点还是部分节点不可用？ 我这边测试是可以的。 手动设置DNS为8.8.8.8试试呢

**Comment by Ender-003** [comment]
> > 似乎也用不了
> 
> 用不了么？ 是所有节点还是部分节点不可用？ 我这边测试是可以的。

现在可以了
