### ISSUE TITLE
多久才能好

### ISSUE THREAD

**Issue by wwlvswwl** [pablocc1979/Green-Hub-Proxy#61]
插件端要多久才能好，以及桌面端好像也暂时没法用

**Comment by ghotst0xdeadbeef** [comment]
> 插件端要多久才能好，以及桌面端好像也暂时没法用

我这边桌面端是可以用的，你这是什么现象？ 换个节点试试呢？   
插件端正在想办法恢复，最近iP封的比较厉害。

**Comment by wwlvswwl** [comment]
现在遇到的问题是网站已拒绝链接

**Comment by ghotst0xdeadbeef** [comment]
close
