### ISSUE TITLE
大家桌面端都连得上吗

### ISSUE THREAD

**Issue by dilidily** [pablocc1979/Green-Hub-Proxy#63]
为啥我的桌面端不管连那个节点，都上不了外网，我就想用个GMail也连不上，节点连上了，但是还是上不了Gmail和youtube

**Comment by blessedbin** [comment]
> 为啥我的桌面端不管连那个节点，都上不了外网，我就想用个GMail也连不上，节点连上了，但是还是上不了Gmail和youtube

DNS 修改为8.8.8.8 也不行么？

**Comment by Ender-003** [comment]
桌面又不行了似乎

**Comment by Ender-003** [comment]
桌面和插件都暂无数据

**Comment by ghotst0xdeadbeef** [comment]
该问题先close了
