### ISSUE TITLE
请问支持配置代理吗？

### ISSUE THREAD

**Issue by shawlj** [pablocc1979/Green-Hub-Proxy#68]
代理配置文件过滤不需要代理的请求URL（或者我没找到配置文件，有教程吗），打开GreenHub桌面客户端不论是选择全局模式还是代理模式，国内主流网站访问很慢更别提其他国内网站了。有网友说DNS配置配置8.8.8.8，经过测试网页加载速度情况并未没有好转。

**Comment by shawlj** [comment]
如果可以将代理设置前置到GUI界面二级菜单进行快速配置。可能要求有点多。抱歉

**Comment by shawlj** [comment]
题外话，发现一个奇怪的现象，就是当github能访问的时候，然后打开刷新或访问国内其他网站，再访问github就会超时，但是过一会又能访问github了，周而复始。等同于我在操作提交或访问github时不能访问任何国内网站，否则IP被限制？

**Comment by ghotst0xdeadbeef** [comment]
pac配置文件的自定义，后面会推出。
另外，DNS可以考虑使用阿里云的公共DNS，这样国内的不受影响。

**Comment by shawlj** [comment]
> pac配置文件的自定义，后面会推出。 另外，DNS可以考虑使用阿里云的公共DNS，这样国内的不受影响。

好的
