### ISSUE TITLE
DNS

### ISSUE THREAD

**Issue by Jeffery-1** [pablocc1979/Green-Hub-Proxy#69]
DNS提示解析失败，MAC用户，两台同配置M1air另一台可以用这一台用不了，DNS都是8.8.8.8可以正常上网。

**Comment by ghotst0xdeadbeef** [comment]
> DNS提示解析失败，MAC用户，两台同配置M1air另一台可以用这一台用不了，DNS都是8.8.8.8可以正常上网。

客户端么？ 可以换成阿里云的DNS
