### ISSUE TITLE
关于隐私

### ISSUE THREAD

**Issue by xxxxxxxb** [pablocc1979/Green-Hub-Proxy#80]
你们会收集用户的隐私吗？
在使用界面没用任何关于隐私的声明，这是否意味着你们会通过收集用户隐私来盈利？
请回答。

**Comment by KeeLee2005** [comment]
> 你们会收集用户的隐私吗？ 在使用界面没用任何关于隐私的声明，这是否意味着你们会通过收集用户隐私来盈利？ 请回答。

开源项目一般不会有违规收集隐私信息的行为，出海后正常使用即可。相较于国内某些大厂而言，隐私毫无价值，所以没有必要将一个非盈利的开放性项目通过收集用户隐私来盈利，这样显得多此一举。尊重开发者的劳动成果和用爱发电行为，且用且珍惜。
